### PR TITLE
New error handling

### PR DESCRIPTION
**Pull request by nxshock**
I hope you can help me to implement new error handling decribed here: #14.

First of all we must fix all of tests to make sure I doing my work right.

### CODE REVIEW

**Comment by kitech** [comment]
In `TestCreate/load_error_profile`, because of given broken profile, the tox2 must nil and err must non-nil.
So that's not your fault.

try assert like this: 

`
            if err == nil || tox2 != nil {
                    t.Error("load broken profile without error?")
            }
`

And at last, below code seems useless, seems need remove them:(because tox2 should be always nil)

`
		if addr == tox2.SelfGetAddress() {
			t.Error("must !=", addr, tox2.SelfGetAddress())
		}
		tox2.Kill()
`

with my test, the err's value is:

> The data format was invalid. This can happen when loading data that was saved by an older version of Tox, or when the data has been corrupted. When loading from badly formatted data, some data may have been loaded, and the rest is discarded. Passing an invalid length parameter also causes this error.

Most sincerely.

**Comment by nxshock** [comment]
Okay, now `TestCreate/load_error_profile` fixed by 74fc2f55cc4dd63b5a07b2ef476c77057e42e422.

But now I have some random crashes... Looks like something goes wrong in C bindings:
<details>
  <summary>Click to expand</summary>
<pre>fatal error: unexpected signal during runtime execution<br>[signal SIGSEGV: segmentation violation code=0x1 addr=0x910 pc=0x7f76b79109ea]<br><br>runtime stack:<br>runtime.throw(0x5fbebc, 0x2a)<br>	/usr/lib/go/src/runtime/panic.go:605 +0x95<br>runtime.sigpanic()<br>	/usr/lib/go/src/runtime/signal_unix.go:351 +0x2b8<br><br>goroutine 22 [syscall, locked to thread]:<br>runtime.cgocall(0x5813b0, 0xc420039f40, 0xc420039f50)<br>	/usr/lib/go/src/runtime/cgocall.go:132 +0xe4 fp=0xc420039f10 sp=0xc420039ed0 pc=0x408324<br>github.com/nxshock/go-toxcore._Cfunc_tox_iterate(0x0, 0x0)<br>	github.com/nxshock/go-toxcore/_test/_obj_test/_cgo_gotypes.go:1734 +0x41 fp=0xc420039f40 sp=0xc420039f10 pc=0x555431<br>github.com/nxshock/go-toxcore.(*Tox).Iterate.func1(0x0, 0x0)<br>	/tmp/go/src/github.com/nxshock/go-toxcore/tox.go:546 +0x6a fp=0xc420039f78 sp=0xc420039f40 pc=0x57c24a<br>github.com/nxshock/go-toxcore.(*Tox).Iterate(0xc4200b0140)<br>	/tmp/go/src/github.com/nxshock/go-toxcore/tox.go:546 +0x4a fp=0xc420039fc0 sp=0xc420039f78 pc=0x56ac0a<br>github.com/nxshock/go-toxcore.TestIssue6.func3(0xc4200b0140)<br>	/tmp/go/src/github.com/nxshock/go-toxcore/group_test.go:41 +0x2b fp=0xc420039fd8 sp=0xc420039fc0 pc=0x570ffb<br>runtime.goexit()<br>	/usr/lib/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc420039fe0 sp=0xc420039fd8 pc=0x461b61<br>created by github.com/nxshock/go-toxcore.TestIssue6<br>	/tmp/go/src/github.com/nxshock/go-toxcore/group_test.go:39 +0x214<br><br>goroutine 1 [chan receive]:<br>testing.(*T).Run(0xc4200a6000, 0x5f39cb, 0x9, 0x5fed68, 0x47da01)<br>	/usr/lib/go/src/testing/testing.go:790 +0x2fc<br>testing.runTests.func1(0xc4200a6000)<br>	/usr/lib/go/src/testing/testing.go:1004 +0x64<br>testing.tRunner(0xc4200a6000, 0xc42004fde0)<br>	/usr/lib/go/src/testing/testing.go:746 +0xd0<br>testing.runTests(0xc420092080, 0x8e9b40, 0xa, 0xa, 0x55e6c8)<br>	/usr/lib/go/src/testing/testing.go:1002 +0x2d8<br>testing.(*M).Run(0xc42004ff18, 0xc42004ff70)<br>	/usr/lib/go/src/testing/testing.go:921 +0x111<br>main.main()<br>	github.com/nxshock/go-toxcore/_test/_testmain.go:62 +0xdb<br><br>goroutine 154 [chan receive]:<br>testing.(*T).Run(0xc42011b2c0, 0x5f33b9, 0x7, 0x5fed60, 0x2f0ac6936)<br>	/usr/lib/go/src/testing/testing.go:790 +0x2fc<br>github.com/nxshock/go-toxcore.TestLogin(0xc42011b2c0)<br>	/tmp/go/src/github.com/nxshock/go-toxcore/tox_test.go:341 +0x4c<br>testing.tRunner(0xc42011b2c0, 0x5fed68)<br>	/usr/lib/go/src/testing/testing.go:746 +0xd0<br>created by testing.(*T).Run<br>	/usr/lib/go/src/testing/testing.go:789 +0x2de<br><br>goroutine 21 [sleep]:<br>time.Sleep(0x11e1a300)<br>	/usr/lib/go/src/runtime/time.go:65 +0x130<br>github.com/nxshock/go-toxcore.TestIssue6.func1(0xc4200b0000)<br>	/tmp/go/src/github.com/nxshock/go-toxcore/group_test.go:23 +0x38<br>created by github.com/nxshock/go-toxcore.TestIssue6<br>	/tmp/go/src/github.com/nxshock/go-toxcore/group_test.go:20 +0x110<br><br>goroutine 155 [sleep]:<br>time.Sleep(0x30a32c0)<br>	/usr/lib/go/src/runtime/time.go:65 +0x130<br>github.com/nxshock/go-toxcore.waitcond(0xc4200b4f80, 0x3c)<br>	/tmp/go/src/github.com/nxshock/go-toxcore/tox_test.go:335 +0x52<br>github.com/nxshock/go-toxcore.TestLogin.func1(0xc42011b3b0)<br>	/tmp/go/src/github.com/nxshock/go-toxcore/tox_test.go:345 +0x9c<br>testing.tRunner(0xc42011b3b0, 0x5fed60)<br>	/usr/lib/go/src/testing/testing.go:746 +0xd0<br>created by testing.(*T).Run<br>	/usr/lib/go/src/testing/testing.go:789 +0x2de<br></pre>
</details>

**Comment by kitech** [comment]
now entered `group_test.go`
need take a look, seems there are nil pointers.

**Comment by nxshock** [comment]
Problem found. This two of loops newer end and panic when tox instanse was killed. Continuing my job.

https://github.com/kitech/go-toxcore/blob/de7063d20c6c708f88ead83c1acdf87fa3bea576/group_test.go#L16-L21

https://github.com/kitech/go-toxcore/blob/de7063d20c6c708f88ead83c1acdf87fa3bea576/group_test.go#L31-L36

**Comment by nxshock** [comment]
Now all tests are fixed. Please review all of changes.

But the tests still need to be reworked (for example, there is no waitcond() timeout check). I will do this in separate PR.

**Pull request merged**
